authentication_required: true
classes:
- colour:
  - 0
  - 255
  - 0
  - 70
  description: Clear pixels where water is not present.
  name: Not-Water
  user_colour:
  - 0
  - 255
  - 255
  - 70
- colour:
  - 0
  - 140
  - 255
  - 70
  description: Clear pixels where water is present.
  name: Water
- colour:
  - 255
  - 255
  - 0
  - 70
  description: Opaque clouds occluding the land or water beneath.
  name: Thick Cloud
- colour:
  - 0
  - 0
  - 0
  - 70
  description: Pixels where no data was captured.
  name: No Data
images:
  metadata: images/{id}/metadata.json
  path:
    sentinel_2: images/{id}/sentinel-2.npy
    blank: blank.npy
  shape:
  - 1000
  - 1000
  thumbnails: images/{id}/thumbnail.png
name: MyProject-sentinel-2
segmentation:
  prioritise_unmarked_images: true
  mask_area:
  - 0
  - 0
  - 1000
  - 1000
  mask_encoding: rgb
  path: images/{id}/mask.png
  score: f1
  test_images: null
  unverified_threshold: 1
view_groups:
  default:
  - Mask
  - RGB
  - NDWI
views:
  Mask:
    data: 
    - $blank.B3
    - $blank.B2
    - $blank.B1
    description: A blank image to show the mask so far.
    type: image
  Cirrus:
    cmap: jet
    data: $sentinel_2.B11**0.8*5
    description: Cirrus and high clouds are red.
    type: image
  NDWI:
    cmap: jet
    data: ($sentinel_2.B3 - $sentinel_2.B8)/($sentinel_2.B3 + $sentinel_2.B8)
    description: Normalised-Difference Water Index
    type: image
  RGB:
    clip: '1'
    data:
    - $sentinel_2.B4
    - $sentinel_2.B3
    - $sentinel_2.B2
    description: Normal RGB image.
    type: image
  Snow:
    data:
    - $sentinel_2.B1
    - $sentinel_2.B12
    - $sentinel_2.B13
    description: Small ice crystals in high-level clouds appear reddish-orange or
      peach, and thick ice snow looks vivid red (or red-orange). Bare soil appears
      bright cyan and vegetation seem greenish in the image. Water on the ground is
      very dark as it absorbs the SWIR and the red, but small (liquid) water drops
      in the clouds scatter the light equally in both visible and the SWIR, and therefore
      it appears white. Water Sediments are displayed as dark red.
    type: image
